// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=core.apinet.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("daemonsets"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().DaemonSets().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ips"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().IPs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipaddresses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().IPAddresses().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("instances"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().Instances().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("loadbalancers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().LoadBalancers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("loadbalancerroutings"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().LoadBalancerRoutings().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("natgateways"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NATGateways().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("natgatewayautoscalers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NATGatewayAutoscalers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("nattables"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NATTables().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().Networks().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networkids"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NetworkIDs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networkinterfaces"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NetworkInterfaces().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NetworkPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("networkpolicyrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().NetworkPolicyRules().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("nodes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Core().V1alpha1().Nodes().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
