// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeLoadBalancers implements LoadBalancerInterface
type fakeLoadBalancers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.LoadBalancer, *v1alpha1.LoadBalancerList, *corev1alpha1.LoadBalancerApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeLoadBalancers(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.LoadBalancerInterface {
	return &fakeLoadBalancers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.LoadBalancer, *v1alpha1.LoadBalancerList, *corev1alpha1.LoadBalancerApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("loadbalancers"),
			v1alpha1.SchemeGroupVersion.WithKind("LoadBalancer"),
			func() *v1alpha1.LoadBalancer { return &v1alpha1.LoadBalancer{} },
			func() *v1alpha1.LoadBalancerList { return &v1alpha1.LoadBalancerList{} },
			func(dst, src *v1alpha1.LoadBalancerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.LoadBalancerList) []*v1alpha1.LoadBalancer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.LoadBalancerList, items []*v1alpha1.LoadBalancer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
