// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPs implements IPInterface
type fakeIPs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.IP, *v1alpha1.IPList, *corev1alpha1.IPApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeIPs(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.IPInterface {
	return &fakeIPs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.IP, *v1alpha1.IPList, *corev1alpha1.IPApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ips"),
			v1alpha1.SchemeGroupVersion.WithKind("IP"),
			func() *v1alpha1.IP { return &v1alpha1.IP{} },
			func() *v1alpha1.IPList { return &v1alpha1.IPList{} },
			func(dst, src *v1alpha1.IPList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPList) []*v1alpha1.IP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPList, items []*v1alpha1.IP) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
