// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInstances implements InstanceInterface
type fakeInstances struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Instance, *v1alpha1.InstanceList, *corev1alpha1.InstanceApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeInstances(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.InstanceInterface {
	return &fakeInstances{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Instance, *v1alpha1.InstanceList, *corev1alpha1.InstanceApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("instances"),
			v1alpha1.SchemeGroupVersion.WithKind("Instance"),
			func() *v1alpha1.Instance { return &v1alpha1.Instance{} },
			func() *v1alpha1.InstanceList { return &v1alpha1.InstanceList{} },
			func(dst, src *v1alpha1.InstanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.InstanceList) []*v1alpha1.Instance { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.InstanceList, items []*v1alpha1.Instance) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
