// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodes implements NodeInterface
type fakeNodes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Node, *v1alpha1.NodeList, *corev1alpha1.NodeApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNodes(fake *FakeCoreV1alpha1) typedcorev1alpha1.NodeInterface {
	return &fakeNodes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Node, *v1alpha1.NodeList, *corev1alpha1.NodeApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("nodes"),
			v1alpha1.SchemeGroupVersion.WithKind("Node"),
			func() *v1alpha1.Node { return &v1alpha1.Node{} },
			func() *v1alpha1.NodeList { return &v1alpha1.NodeList{} },
			func(dst, src *v1alpha1.NodeList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NodeList) []*v1alpha1.Node { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NodeList, items []*v1alpha1.Node) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
