// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetworks implements NetworkInterface
type fakeNetworks struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Network, *v1alpha1.NetworkList, *corev1alpha1.NetworkApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNetworks(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.NetworkInterface {
	return &fakeNetworks{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Network, *v1alpha1.NetworkList, *corev1alpha1.NetworkApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("networks"),
			v1alpha1.SchemeGroupVersion.WithKind("Network"),
			func() *v1alpha1.Network { return &v1alpha1.Network{} },
			func() *v1alpha1.NetworkList { return &v1alpha1.NetworkList{} },
			func(dst, src *v1alpha1.NetworkList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NetworkList) []*v1alpha1.Network { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NetworkList, items []*v1alpha1.Network) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
