// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetworkIDs implements NetworkIDInterface
type fakeNetworkIDs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NetworkID, *v1alpha1.NetworkIDList, *corev1alpha1.NetworkIDApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNetworkIDs(fake *FakeCoreV1alpha1) typedcorev1alpha1.NetworkIDInterface {
	return &fakeNetworkIDs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NetworkID, *v1alpha1.NetworkIDList, *corev1alpha1.NetworkIDApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("networkids"),
			v1alpha1.SchemeGroupVersion.WithKind("NetworkID"),
			func() *v1alpha1.NetworkID { return &v1alpha1.NetworkID{} },
			func() *v1alpha1.NetworkIDList { return &v1alpha1.NetworkIDList{} },
			func(dst, src *v1alpha1.NetworkIDList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NetworkIDList) []*v1alpha1.NetworkID { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NetworkIDList, items []*v1alpha1.NetworkID) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
