// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetworkPolicyRules implements NetworkPolicyRuleInterface
type fakeNetworkPolicyRules struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NetworkPolicyRule, *v1alpha1.NetworkPolicyRuleList, *corev1alpha1.NetworkPolicyRuleApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNetworkPolicyRules(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.NetworkPolicyRuleInterface {
	return &fakeNetworkPolicyRules{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NetworkPolicyRule, *v1alpha1.NetworkPolicyRuleList, *corev1alpha1.NetworkPolicyRuleApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("networkpolicyrules"),
			v1alpha1.SchemeGroupVersion.WithKind("NetworkPolicyRule"),
			func() *v1alpha1.NetworkPolicyRule { return &v1alpha1.NetworkPolicyRule{} },
			func() *v1alpha1.NetworkPolicyRuleList { return &v1alpha1.NetworkPolicyRuleList{} },
			func(dst, src *v1alpha1.NetworkPolicyRuleList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NetworkPolicyRuleList) []*v1alpha1.NetworkPolicyRule {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.NetworkPolicyRuleList, items []*v1alpha1.NetworkPolicyRule) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
