// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNATTables implements NATTableInterface
type fakeNATTables struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NATTable, *v1alpha1.NATTableList, *corev1alpha1.NATTableApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNATTables(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.NATTableInterface {
	return &fakeNATTables{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NATTable, *v1alpha1.NATTableList, *corev1alpha1.NATTableApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("nattables"),
			v1alpha1.SchemeGroupVersion.WithKind("NATTable"),
			func() *v1alpha1.NATTable { return &v1alpha1.NATTable{} },
			func() *v1alpha1.NATTableList { return &v1alpha1.NATTableList{} },
			func(dst, src *v1alpha1.NATTableList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NATTableList) []*v1alpha1.NATTable { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NATTableList, items []*v1alpha1.NATTable) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
