// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNATGatewayAutoscalers implements NATGatewayAutoscalerInterface
type fakeNATGatewayAutoscalers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NATGatewayAutoscaler, *v1alpha1.NATGatewayAutoscalerList, *corev1alpha1.NATGatewayAutoscalerApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNATGatewayAutoscalers(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.NATGatewayAutoscalerInterface {
	return &fakeNATGatewayAutoscalers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NATGatewayAutoscaler, *v1alpha1.NATGatewayAutoscalerList, *corev1alpha1.NATGatewayAutoscalerApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("natgatewayautoscalers"),
			v1alpha1.SchemeGroupVersion.WithKind("NATGatewayAutoscaler"),
			func() *v1alpha1.NATGatewayAutoscaler { return &v1alpha1.NATGatewayAutoscaler{} },
			func() *v1alpha1.NATGatewayAutoscalerList { return &v1alpha1.NATGatewayAutoscalerList{} },
			func(dst, src *v1alpha1.NATGatewayAutoscalerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NATGatewayAutoscalerList) []*v1alpha1.NATGatewayAutoscaler {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.NATGatewayAutoscalerList, items []*v1alpha1.NATGatewayAutoscaler) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
