// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNATGateways implements NATGatewayInterface
type fakeNATGateways struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NATGateway, *v1alpha1.NATGatewayList, *corev1alpha1.NATGatewayApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeNATGateways(fake *FakeCoreV1alpha1, namespace string) typedcorev1alpha1.NATGatewayInterface {
	return &fakeNATGateways{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NATGateway, *v1alpha1.NATGatewayList, *corev1alpha1.NATGatewayApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("natgateways"),
			v1alpha1.SchemeGroupVersion.WithKind("NATGateway"),
			func() *v1alpha1.NATGateway { return &v1alpha1.NATGateway{} },
			func() *v1alpha1.NATGatewayList { return &v1alpha1.NATGatewayList{} },
			func(dst, src *v1alpha1.NATGatewayList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NATGatewayList) []*v1alpha1.NATGateway { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NATGatewayList, items []*v1alpha1.NATGateway) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
