// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	typedcorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAddresses implements IPAddressInterface
type fakeIPAddresses struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.IPAddress, *v1alpha1.IPAddressList, *corev1alpha1.IPAddressApplyConfiguration]
	Fake *FakeCoreV1alpha1
}

func newFakeIPAddresses(fake *FakeCoreV1alpha1) typedcorev1alpha1.IPAddressInterface {
	return &fakeIPAddresses{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.IPAddress, *v1alpha1.IPAddressList, *corev1alpha1.IPAddressApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("ipaddresses"),
			v1alpha1.SchemeGroupVersion.WithKind("IPAddress"),
			func() *v1alpha1.IPAddress { return &v1alpha1.IPAddress{} },
			func() *v1alpha1.IPAddressList { return &v1alpha1.IPAddressList{} },
			func(dst, src *v1alpha1.IPAddressList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPAddressList) []*v1alpha1.IPAddress { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPAddressList, items []*v1alpha1.IPAddress) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
