apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.core.apinet.ironcore.dev
spec:
  group: core.apinet.ironcore.dev
  version: v1alpha1
  service:
    namespace: system
    name: apiserver-service
  groupPriorityMinimum: 1900
  versionPriority: 90
