//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright (c) 2022 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/onmetal/onmetal-api-net/api/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&v1alpha1.IP{}, func(obj interface{}) { SetObjectDefaults_IP(obj.(*v1alpha1.IP)) })
	scheme.AddTypeDefaultingFunc(&v1alpha1.IPList{}, func(obj interface{}) { SetObjectDefaults_IPList(obj.(*v1alpha1.IPList)) })
	return nil
}

func SetObjectDefaults_IP(in *v1alpha1.IP) {
	SetDefaults_IPSpec(&in.Spec)
}

func SetObjectDefaults_IPList(in *v1alpha1.IPList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_IP(a)
	}
}
