apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patchesStrategicMerge:
  - patch-controller.yaml
  
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: onmetal-api-net-system
      name: onmetal-api-net-controller-manager
    path: add-manager-args.yaml
