apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

  
patches:
- path: add-manager-args.yaml
  target:
    group: apps
    kind: Deployment
    name: ironcore-net-controller-manager
    namespace: ironcore-net-system
    version: v1
- path: patch-controller.yaml
