apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ironcore-net-system
  name: ironcore-net-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
