apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apinetlet-system
namePrefix: apinetlet-

resources:
  - ../../apinet-rbac

patches:
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: controller-manager
        namespace: system
