//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package net

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.apimachinery.api.net.IP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPrefix) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.apimachinery.api.net.IPPrefix"
}
