// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DaemonSetListerExpansion allows custom methods to be added to
// DaemonSetLister.
type DaemonSetListerExpansion interface{}

// DaemonSetNamespaceListerExpansion allows custom methods to be added to
// DaemonSetNamespaceLister.
type DaemonSetNamespaceListerExpansion interface{}

// IPListerExpansion allows custom methods to be added to
// IPLister.
type IPListerExpansion interface{}

// IPNamespaceListerExpansion allows custom methods to be added to
// IPNamespaceLister.
type IPNamespaceListerExpansion interface{}

// IPAddressListerExpansion allows custom methods to be added to
// IPAddressLister.
type IPAddressListerExpansion interface{}

// InstanceListerExpansion allows custom methods to be added to
// InstanceLister.
type InstanceListerExpansion interface{}

// InstanceNamespaceListerExpansion allows custom methods to be added to
// InstanceNamespaceLister.
type InstanceNamespaceListerExpansion interface{}

// LoadBalancerListerExpansion allows custom methods to be added to
// LoadBalancerLister.
type LoadBalancerListerExpansion interface{}

// LoadBalancerNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerNamespaceLister.
type LoadBalancerNamespaceListerExpansion interface{}

// LoadBalancerRoutingListerExpansion allows custom methods to be added to
// LoadBalancerRoutingLister.
type LoadBalancerRoutingListerExpansion interface{}

// LoadBalancerRoutingNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerRoutingNamespaceLister.
type LoadBalancerRoutingNamespaceListerExpansion interface{}

// NATGatewayListerExpansion allows custom methods to be added to
// NATGatewayLister.
type NATGatewayListerExpansion interface{}

// NATGatewayNamespaceListerExpansion allows custom methods to be added to
// NATGatewayNamespaceLister.
type NATGatewayNamespaceListerExpansion interface{}

// NATGatewayAutoscalerListerExpansion allows custom methods to be added to
// NATGatewayAutoscalerLister.
type NATGatewayAutoscalerListerExpansion interface{}

// NATGatewayAutoscalerNamespaceListerExpansion allows custom methods to be added to
// NATGatewayAutoscalerNamespaceLister.
type NATGatewayAutoscalerNamespaceListerExpansion interface{}

// NATTableListerExpansion allows custom methods to be added to
// NATTableLister.
type NATTableListerExpansion interface{}

// NATTableNamespaceListerExpansion allows custom methods to be added to
// NATTableNamespaceLister.
type NATTableNamespaceListerExpansion interface{}

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}

// NetworkIDListerExpansion allows custom methods to be added to
// NetworkIDLister.
type NetworkIDListerExpansion interface{}

// NetworkInterfaceListerExpansion allows custom methods to be added to
// NetworkInterfaceLister.
type NetworkInterfaceListerExpansion interface{}

// NetworkInterfaceNamespaceListerExpansion allows custom methods to be added to
// NetworkInterfaceNamespaceLister.
type NetworkInterfaceNamespaceListerExpansion interface{}

// NetworkPolicyListerExpansion allows custom methods to be added to
// NetworkPolicyLister.
type NetworkPolicyListerExpansion interface{}

// NetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// NetworkPolicyNamespaceLister.
type NetworkPolicyNamespaceListerExpansion interface{}

// NetworkPolicyRuleListerExpansion allows custom methods to be added to
// NetworkPolicyRuleLister.
type NetworkPolicyRuleListerExpansion interface{}

// NetworkPolicyRuleNamespaceListerExpansion allows custom methods to be added to
// NetworkPolicyRuleNamespaceLister.
type NetworkPolicyRuleNamespaceListerExpansion interface{}

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion interface{}
