// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkPolicyRuleLister helps list NetworkPolicyRules.
// All objects returned here must be treated as read-only.
type NetworkPolicyRuleLister interface {
	// List lists all NetworkPolicyRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkPolicyRule, err error)
	// NetworkPolicyRules returns an object that can list and get NetworkPolicyRules.
	NetworkPolicyRules(namespace string) NetworkPolicyRuleNamespaceLister
	NetworkPolicyRuleListerExpansion
}

// networkPolicyRuleLister implements the NetworkPolicyRuleLister interface.
type networkPolicyRuleLister struct {
	indexer cache.Indexer
}

// NewNetworkPolicyRuleLister returns a new NetworkPolicyRuleLister.
func NewNetworkPolicyRuleLister(indexer cache.Indexer) NetworkPolicyRuleLister {
	return &networkPolicyRuleLister{indexer: indexer}
}

// List lists all NetworkPolicyRules in the indexer.
func (s *networkPolicyRuleLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkPolicyRule, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkPolicyRule))
	})
	return ret, err
}

// NetworkPolicyRules returns an object that can list and get NetworkPolicyRules.
func (s *networkPolicyRuleLister) NetworkPolicyRules(namespace string) NetworkPolicyRuleNamespaceLister {
	return networkPolicyRuleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NetworkPolicyRuleNamespaceLister helps list and get NetworkPolicyRules.
// All objects returned here must be treated as read-only.
type NetworkPolicyRuleNamespaceLister interface {
	// List lists all NetworkPolicyRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NetworkPolicyRule, err error)
	// Get retrieves the NetworkPolicyRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NetworkPolicyRule, error)
	NetworkPolicyRuleNamespaceListerExpansion
}

// networkPolicyRuleNamespaceLister implements the NetworkPolicyRuleNamespaceLister
// interface.
type networkPolicyRuleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NetworkPolicyRules in the indexer for a given namespace.
func (s networkPolicyRuleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.NetworkPolicyRule, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NetworkPolicyRule))
	})
	return ret, err
}

// Get retrieves the NetworkPolicyRule from the indexer for a given namespace and name.
func (s networkPolicyRuleNamespaceLister) Get(name string) (*v1alpha1.NetworkPolicyRule, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("networkpolicyrule"), name)
	}
	return obj.(*v1alpha1.NetworkPolicyRule), nil
}
