//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Affinity) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.Affinity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DaemonSet) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.DaemonSet"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DaemonSetList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.DaemonSetList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DaemonSetSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.DaemonSetSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DaemonSetStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.DaemonSetStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAddress) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPAddress"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAddressClaimRef) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPAddressClaimRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAddressList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPAddressList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAddressSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPAddressSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPBlock) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPBlock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPClaimRef) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPClaimRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.IPStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Instance) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.Instance"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InstanceAffinityTerm) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.InstanceAffinityTerm"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InstanceAntiAffinity) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.InstanceAntiAffinity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InstanceList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.InstanceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InstanceSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.InstanceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InstanceStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.InstanceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in InstanceTemplate) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.InstanceTemplate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancer) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerDestination) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerDestination"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerIP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerPort) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerRouting) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerRouting"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerRoutingList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerRoutingList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalancerTargetRef) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LoadBalancerTargetRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalUIDReference) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.LocalUIDReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGateway) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGateway"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayAutoscaler) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayAutoscaler"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayAutoscalerList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayAutoscalerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayAutoscalerSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayAutoscalerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayAutoscalerStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayAutoscalerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayIP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewaySpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewaySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATGatewayStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATIP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATIPSection) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATIPSection"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATTable) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATTable"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATTableIPTargetRef) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATTableIPTargetRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NATTableList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATTableList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Network) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.Network"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkID) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkID"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkIDClaimRef) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkIDClaimRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkIDList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkIDList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkIDSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkIDSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterface) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterfaceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceNAT) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterfaceNAT"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceNATClaimRef) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterfaceNATClaimRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfacePublicIP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterfacePublicIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterfaceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkInterfaceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPeering) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPeering"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPeeringStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPeeringStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicy) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyEgressRule) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyEgressRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyIngressRule) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyIngressRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyPeer) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyPeer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyPort) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyRule) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyRuleList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicyRuleList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NetworkStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Node) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.Node"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeAffinity) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeAffinity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeSelector) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeSelectorRequirement) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeSelectorRequirement"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeSelectorTerm) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeSelectorTerm"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NodeStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObjectIP) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.ObjectIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObjectSelector) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.ObjectSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PCIAddress) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.PCIAddress"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PeeringPrefix) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.PeeringPrefix"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Rule) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.Rule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TAPDevice) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.TAPDevice"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TargetNetworkInterface) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.TargetNetworkInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TopologySpreadConstraint) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.TopologySpreadConstraint"
}
