// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	"github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type CoreV1alpha1Interface interface {
	RESTClient() rest.Interface
	DaemonSetsGetter
	IPsGetter
	IPAddressesGetter
	InstancesGetter
	LoadBalancersGetter
	LoadBalancerRoutingsGetter
	NATGatewaysGetter
	NATGatewayAutoscalersGetter
	NATTablesGetter
	NetworksGetter
	NetworkIDsGetter
	NetworkInterfacesGetter
	NetworkPoliciesGetter
	NetworkPolicyRulesGetter
	NodesGetter
}

// CoreV1alpha1Client is used to interact with features provided by the core.apinet.ironcore.dev group.
type CoreV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CoreV1alpha1Client) DaemonSets(namespace string) DaemonSetInterface {
	return newDaemonSets(c, namespace)
}

func (c *CoreV1alpha1Client) IPs(namespace string) IPInterface {
	return newIPs(c, namespace)
}

func (c *CoreV1alpha1Client) IPAddresses() IPAddressInterface {
	return newIPAddresses(c)
}

func (c *CoreV1alpha1Client) Instances(namespace string) InstanceInterface {
	return newInstances(c, namespace)
}

func (c *CoreV1alpha1Client) LoadBalancers(namespace string) LoadBalancerInterface {
	return newLoadBalancers(c, namespace)
}

func (c *CoreV1alpha1Client) LoadBalancerRoutings(namespace string) LoadBalancerRoutingInterface {
	return newLoadBalancerRoutings(c, namespace)
}

func (c *CoreV1alpha1Client) NATGateways(namespace string) NATGatewayInterface {
	return newNATGateways(c, namespace)
}

func (c *CoreV1alpha1Client) NATGatewayAutoscalers(namespace string) NATGatewayAutoscalerInterface {
	return newNATGatewayAutoscalers(c, namespace)
}

func (c *CoreV1alpha1Client) NATTables(namespace string) NATTableInterface {
	return newNATTables(c, namespace)
}

func (c *CoreV1alpha1Client) Networks(namespace string) NetworkInterface {
	return newNetworks(c, namespace)
}

func (c *CoreV1alpha1Client) NetworkIDs() NetworkIDInterface {
	return newNetworkIDs(c)
}

func (c *CoreV1alpha1Client) NetworkInterfaces(namespace string) NetworkInterfaceInterface {
	return newNetworkInterfaces(c, namespace)
}

func (c *CoreV1alpha1Client) NetworkPolicies(namespace string) NetworkPolicyInterface {
	return newNetworkPolicies(c, namespace)
}

func (c *CoreV1alpha1Client) NetworkPolicyRules(namespace string) NetworkPolicyRuleInterface {
	return newNetworkPolicyRules(c, namespace)
}

func (c *CoreV1alpha1Client) Nodes() NodeInterface {
	return newNodes(c)
}

// NewForConfig creates a new CoreV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*CoreV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new CoreV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*CoreV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &CoreV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CoreV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CoreV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CoreV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CoreV1alpha1Client {
	return &CoreV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CoreV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
