// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	applyconfigurationscorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LoadBalancerRoutingsGetter has a method to return a LoadBalancerRoutingInterface.
// A group's client should implement this interface.
type LoadBalancerRoutingsGetter interface {
	LoadBalancerRoutings(namespace string) LoadBalancerRoutingInterface
}

// LoadBalancerRoutingInterface has methods to work with LoadBalancerRouting resources.
type LoadBalancerRoutingInterface interface {
	Create(ctx context.Context, loadBalancerRouting *corev1alpha1.LoadBalancerRouting, opts v1.CreateOptions) (*corev1alpha1.LoadBalancerRouting, error)
	Update(ctx context.Context, loadBalancerRouting *corev1alpha1.LoadBalancerRouting, opts v1.UpdateOptions) (*corev1alpha1.LoadBalancerRouting, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.LoadBalancerRouting, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.LoadBalancerRoutingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.LoadBalancerRouting, err error)
	Apply(ctx context.Context, loadBalancerRouting *applyconfigurationscorev1alpha1.LoadBalancerRoutingApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.LoadBalancerRouting, err error)
	LoadBalancerRoutingExpansion
}

// loadBalancerRoutings implements LoadBalancerRoutingInterface
type loadBalancerRoutings struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.LoadBalancerRouting, *corev1alpha1.LoadBalancerRoutingList, *applyconfigurationscorev1alpha1.LoadBalancerRoutingApplyConfiguration]
}

// newLoadBalancerRoutings returns a LoadBalancerRoutings
func newLoadBalancerRoutings(c *CoreV1alpha1Client, namespace string) *loadBalancerRoutings {
	return &loadBalancerRoutings{
		gentype.NewClientWithListAndApply[*corev1alpha1.LoadBalancerRouting, *corev1alpha1.LoadBalancerRoutingList, *applyconfigurationscorev1alpha1.LoadBalancerRoutingApplyConfiguration](
			"loadbalancerroutings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.LoadBalancerRouting { return &corev1alpha1.LoadBalancerRouting{} },
			func() *corev1alpha1.LoadBalancerRoutingList { return &corev1alpha1.LoadBalancerRoutingList{} },
		),
	}
}
