// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	applyconfigurationscorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LoadBalancersGetter has a method to return a LoadBalancerInterface.
// A group's client should implement this interface.
type LoadBalancersGetter interface {
	LoadBalancers(namespace string) LoadBalancerInterface
}

// LoadBalancerInterface has methods to work with LoadBalancer resources.
type LoadBalancerInterface interface {
	Create(ctx context.Context, loadBalancer *corev1alpha1.LoadBalancer, opts v1.CreateOptions) (*corev1alpha1.LoadBalancer, error)
	Update(ctx context.Context, loadBalancer *corev1alpha1.LoadBalancer, opts v1.UpdateOptions) (*corev1alpha1.LoadBalancer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, loadBalancer *corev1alpha1.LoadBalancer, opts v1.UpdateOptions) (*corev1alpha1.LoadBalancer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.LoadBalancer, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.LoadBalancerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.LoadBalancer, err error)
	Apply(ctx context.Context, loadBalancer *applyconfigurationscorev1alpha1.LoadBalancerApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.LoadBalancer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, loadBalancer *applyconfigurationscorev1alpha1.LoadBalancerApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.LoadBalancer, err error)
	LoadBalancerExpansion
}

// loadBalancers implements LoadBalancerInterface
type loadBalancers struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.LoadBalancer, *corev1alpha1.LoadBalancerList, *applyconfigurationscorev1alpha1.LoadBalancerApplyConfiguration]
}

// newLoadBalancers returns a LoadBalancers
func newLoadBalancers(c *CoreV1alpha1Client, namespace string) *loadBalancers {
	return &loadBalancers{
		gentype.NewClientWithListAndApply[*corev1alpha1.LoadBalancer, *corev1alpha1.LoadBalancerList, *applyconfigurationscorev1alpha1.LoadBalancerApplyConfiguration](
			"loadbalancers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.LoadBalancer { return &corev1alpha1.LoadBalancer{} },
			func() *corev1alpha1.LoadBalancerList { return &corev1alpha1.LoadBalancerList{} },
		),
	}
}
