// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NATGatewayAutoscalersGetter has a method to return a NATGatewayAutoscalerInterface.
// A group's client should implement this interface.
type NATGatewayAutoscalersGetter interface {
	NATGatewayAutoscalers(namespace string) NATGatewayAutoscalerInterface
}

// NATGatewayAutoscalerInterface has methods to work with NATGatewayAutoscaler resources.
type NATGatewayAutoscalerInterface interface {
	Create(ctx context.Context, nATGatewayAutoscaler *v1alpha1.NATGatewayAutoscaler, opts v1.CreateOptions) (*v1alpha1.NATGatewayAutoscaler, error)
	Update(ctx context.Context, nATGatewayAutoscaler *v1alpha1.NATGatewayAutoscaler, opts v1.UpdateOptions) (*v1alpha1.NATGatewayAutoscaler, error)
	UpdateStatus(ctx context.Context, nATGatewayAutoscaler *v1alpha1.NATGatewayAutoscaler, opts v1.UpdateOptions) (*v1alpha1.NATGatewayAutoscaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NATGatewayAutoscaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NATGatewayAutoscalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NATGatewayAutoscaler, err error)
	Apply(ctx context.Context, nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscalerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NATGatewayAutoscaler, err error)
	ApplyStatus(ctx context.Context, nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscalerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NATGatewayAutoscaler, err error)
	NATGatewayAutoscalerExpansion
}

// nATGatewayAutoscalers implements NATGatewayAutoscalerInterface
type nATGatewayAutoscalers struct {
	client rest.Interface
	ns     string
}

// newNATGatewayAutoscalers returns a NATGatewayAutoscalers
func newNATGatewayAutoscalers(c *CoreV1alpha1Client, namespace string) *nATGatewayAutoscalers {
	return &nATGatewayAutoscalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nATGatewayAutoscaler, and returns the corresponding nATGatewayAutoscaler object, and an error if there is any.
func (c *nATGatewayAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NATGatewayAutoscalers that match those selectors.
func (c *nATGatewayAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NATGatewayAutoscalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NATGatewayAutoscalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nATGatewayAutoscalers.
func (c *nATGatewayAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nATGatewayAutoscaler and creates it.  Returns the server's representation of the nATGatewayAutoscaler, and an error, if there is any.
func (c *nATGatewayAutoscalers) Create(ctx context.Context, nATGatewayAutoscaler *v1alpha1.NATGatewayAutoscaler, opts v1.CreateOptions) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nATGatewayAutoscaler).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nATGatewayAutoscaler and updates it. Returns the server's representation of the nATGatewayAutoscaler, and an error, if there is any.
func (c *nATGatewayAutoscalers) Update(ctx context.Context, nATGatewayAutoscaler *v1alpha1.NATGatewayAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(nATGatewayAutoscaler.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nATGatewayAutoscaler).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nATGatewayAutoscalers) UpdateStatus(ctx context.Context, nATGatewayAutoscaler *v1alpha1.NATGatewayAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(nATGatewayAutoscaler.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nATGatewayAutoscaler).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nATGatewayAutoscaler and deletes it. Returns an error if one occurs.
func (c *nATGatewayAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nATGatewayAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nATGatewayAutoscaler.
func (c *nATGatewayAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nATGatewayAutoscaler.
func (c *nATGatewayAutoscalers) Apply(ctx context.Context, nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscalerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	if nATGatewayAutoscaler == nil {
		return nil, fmt.Errorf("nATGatewayAutoscaler provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nATGatewayAutoscaler)
	if err != nil {
		return nil, err
	}
	name := nATGatewayAutoscaler.Name
	if name == nil {
		return nil, fmt.Errorf("nATGatewayAutoscaler.Name must be provided to Apply")
	}
	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *nATGatewayAutoscalers) ApplyStatus(ctx context.Context, nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscalerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NATGatewayAutoscaler, err error) {
	if nATGatewayAutoscaler == nil {
		return nil, fmt.Errorf("nATGatewayAutoscaler provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nATGatewayAutoscaler)
	if err != nil {
		return nil, err
	}

	name := nATGatewayAutoscaler.Name
	if name == nil {
		return nil, fmt.Errorf("nATGatewayAutoscaler.Name must be provided to Apply")
	}

	result = &v1alpha1.NATGatewayAutoscaler{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("natgatewayautoscalers").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
