// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	applyconfigurationscorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NATGatewaysGetter has a method to return a NATGatewayInterface.
// A group's client should implement this interface.
type NATGatewaysGetter interface {
	NATGateways(namespace string) NATGatewayInterface
}

// NATGatewayInterface has methods to work with NATGateway resources.
type NATGatewayInterface interface {
	Create(ctx context.Context, nATGateway *corev1alpha1.NATGateway, opts v1.CreateOptions) (*corev1alpha1.NATGateway, error)
	Update(ctx context.Context, nATGateway *corev1alpha1.NATGateway, opts v1.UpdateOptions) (*corev1alpha1.NATGateway, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nATGateway *corev1alpha1.NATGateway, opts v1.UpdateOptions) (*corev1alpha1.NATGateway, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.NATGateway, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.NATGatewayList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.NATGateway, err error)
	Apply(ctx context.Context, nATGateway *applyconfigurationscorev1alpha1.NATGatewayApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.NATGateway, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, nATGateway *applyconfigurationscorev1alpha1.NATGatewayApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.NATGateway, err error)
	NATGatewayExpansion
}

// nATGateways implements NATGatewayInterface
type nATGateways struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.NATGateway, *corev1alpha1.NATGatewayList, *applyconfigurationscorev1alpha1.NATGatewayApplyConfiguration]
}

// newNATGateways returns a NATGateways
func newNATGateways(c *CoreV1alpha1Client, namespace string) *nATGateways {
	return &nATGateways{
		gentype.NewClientWithListAndApply[*corev1alpha1.NATGateway, *corev1alpha1.NATGatewayList, *applyconfigurationscorev1alpha1.NATGatewayApplyConfiguration](
			"natgateways",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.NATGateway { return &corev1alpha1.NATGateway{} },
			func() *corev1alpha1.NATGatewayList { return &corev1alpha1.NATGatewayList{} },
		),
	}
}
