// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkIDsGetter has a method to return a NetworkIDInterface.
// A group's client should implement this interface.
type NetworkIDsGetter interface {
	NetworkIDs() NetworkIDInterface
}

// NetworkIDInterface has methods to work with NetworkID resources.
type NetworkIDInterface interface {
	Create(ctx context.Context, networkID *v1alpha1.NetworkID, opts v1.CreateOptions) (*v1alpha1.NetworkID, error)
	Update(ctx context.Context, networkID *v1alpha1.NetworkID, opts v1.UpdateOptions) (*v1alpha1.NetworkID, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NetworkID, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NetworkIDList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkID, err error)
	Apply(ctx context.Context, networkID *corev1alpha1.NetworkIDApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkID, err error)
	NetworkIDExpansion
}

// networkIDs implements NetworkIDInterface
type networkIDs struct {
	client rest.Interface
}

// newNetworkIDs returns a NetworkIDs
func newNetworkIDs(c *CoreV1alpha1Client) *networkIDs {
	return &networkIDs{
		client: c.RESTClient(),
	}
}

// Get takes name of the networkID, and returns the corresponding networkID object, and an error if there is any.
func (c *networkIDs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkID, err error) {
	result = &v1alpha1.NetworkID{}
	err = c.client.Get().
		Resource("networkids").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkIDs that match those selectors.
func (c *networkIDs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkIDList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkIDList{}
	err = c.client.Get().
		Resource("networkids").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkIDs.
func (c *networkIDs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("networkids").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkID and creates it.  Returns the server's representation of the networkID, and an error, if there is any.
func (c *networkIDs) Create(ctx context.Context, networkID *v1alpha1.NetworkID, opts v1.CreateOptions) (result *v1alpha1.NetworkID, err error) {
	result = &v1alpha1.NetworkID{}
	err = c.client.Post().
		Resource("networkids").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkID).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkID and updates it. Returns the server's representation of the networkID, and an error, if there is any.
func (c *networkIDs) Update(ctx context.Context, networkID *v1alpha1.NetworkID, opts v1.UpdateOptions) (result *v1alpha1.NetworkID, err error) {
	result = &v1alpha1.NetworkID{}
	err = c.client.Put().
		Resource("networkids").
		Name(networkID.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkID).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkID and deletes it. Returns an error if one occurs.
func (c *networkIDs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("networkids").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkIDs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("networkids").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkID.
func (c *networkIDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkID, err error) {
	result = &v1alpha1.NetworkID{}
	err = c.client.Patch(pt).
		Resource("networkids").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkID.
func (c *networkIDs) Apply(ctx context.Context, networkID *corev1alpha1.NetworkIDApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkID, err error) {
	if networkID == nil {
		return nil, fmt.Errorf("networkID provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(networkID)
	if err != nil {
		return nil, err
	}
	name := networkID.Name
	if name == nil {
		return nil, fmt.Errorf("networkID.Name must be provided to Apply")
	}
	result = &v1alpha1.NetworkID{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("networkids").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
