// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	applyconfigurationscorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworksGetter has a method to return a NetworkInterface.
// A group's client should implement this interface.
type NetworksGetter interface {
	Networks(namespace string) NetworkInterface
}

// NetworkInterface has methods to work with Network resources.
type NetworkInterface interface {
	Create(ctx context.Context, network *corev1alpha1.Network, opts v1.CreateOptions) (*corev1alpha1.Network, error)
	Update(ctx context.Context, network *corev1alpha1.Network, opts v1.UpdateOptions) (*corev1alpha1.Network, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, network *corev1alpha1.Network, opts v1.UpdateOptions) (*corev1alpha1.Network, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.Network, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.NetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.Network, err error)
	Apply(ctx context.Context, network *applyconfigurationscorev1alpha1.NetworkApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.Network, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, network *applyconfigurationscorev1alpha1.NetworkApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.Network, err error)
	NetworkExpansion
}

// networks implements NetworkInterface
type networks struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.Network, *corev1alpha1.NetworkList, *applyconfigurationscorev1alpha1.NetworkApplyConfiguration]
}

// newNetworks returns a Networks
func newNetworks(c *CoreV1alpha1Client, namespace string) *networks {
	return &networks{
		gentype.NewClientWithListAndApply[*corev1alpha1.Network, *corev1alpha1.NetworkList, *applyconfigurationscorev1alpha1.NetworkApplyConfiguration](
			"networks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.Network { return &corev1alpha1.Network{} },
			func() *corev1alpha1.NetworkList { return &corev1alpha1.NetworkList{} },
		),
	}
}
