// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	applyconfigurationscorev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NodesGetter has a method to return a NodeInterface.
// A group's client should implement this interface.
type NodesGetter interface {
	Nodes() NodeInterface
}

// NodeInterface has methods to work with Node resources.
type NodeInterface interface {
	Create(ctx context.Context, node *corev1alpha1.Node, opts v1.CreateOptions) (*corev1alpha1.Node, error)
	Update(ctx context.Context, node *corev1alpha1.Node, opts v1.UpdateOptions) (*corev1alpha1.Node, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, node *corev1alpha1.Node, opts v1.UpdateOptions) (*corev1alpha1.Node, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.Node, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.NodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.Node, err error)
	Apply(ctx context.Context, node *applyconfigurationscorev1alpha1.NodeApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.Node, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, node *applyconfigurationscorev1alpha1.NodeApplyConfiguration, opts v1.ApplyOptions) (result *corev1alpha1.Node, err error)
	NodeExpansion
}

// nodes implements NodeInterface
type nodes struct {
	*gentype.ClientWithListAndApply[*corev1alpha1.Node, *corev1alpha1.NodeList, *applyconfigurationscorev1alpha1.NodeApplyConfiguration]
}

// newNodes returns a Nodes
func newNodes(c *CoreV1alpha1Client) *nodes {
	return &nodes{
		gentype.NewClientWithListAndApply[*corev1alpha1.Node, *corev1alpha1.NodeList, *applyconfigurationscorev1alpha1.NodeApplyConfiguration](
			"nodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha1.Node { return &corev1alpha1.Node{} },
			func() *corev1alpha1.NodeList { return &corev1alpha1.NodeList{} },
		),
	}
}
