// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// IPAddressClaimRefApplyConfiguration represents a declarative configuration of the IPAddressClaimRef type for use
// with apply.
type IPAddressClaimRefApplyConfiguration struct {
	Group     *string    `json:"group,omitempty"`
	Resource  *string    `json:"resource,omitempty"`
	Namespace *string    `json:"namespace,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UID       *types.UID `json:"uid,omitempty"`
}

// IPAddressClaimRefApplyConfiguration constructs a declarative configuration of the IPAddressClaimRef type for use with
// apply.
func IPAddressClaimRef() *IPAddressClaimRefApplyConfiguration {
	return &IPAddressClaimRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *IPAddressClaimRefApplyConfiguration) WithGroup(value string) *IPAddressClaimRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *IPAddressClaimRefApplyConfiguration) WithResource(value string) *IPAddressClaimRefApplyConfiguration {
	b.Resource = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *IPAddressClaimRefApplyConfiguration) WithNamespace(value string) *IPAddressClaimRefApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IPAddressClaimRefApplyConfiguration) WithName(value string) *IPAddressClaimRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *IPAddressClaimRefApplyConfiguration) WithUID(value types.UID) *IPAddressClaimRefApplyConfiguration {
	b.UID = &value
	return b
}
