// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// IPClaimRefApplyConfiguration represents a declarative configuration of the IPClaimRef type for use
// with apply.
type IPClaimRefApplyConfiguration struct {
	Group    *string    `json:"group,omitempty"`
	Resource *string    `json:"resource,omitempty"`
	Name     *string    `json:"name,omitempty"`
	UID      *types.UID `json:"uid,omitempty"`
}

// IPClaimRefApplyConfiguration constructs a declarative configuration of the IPClaimRef type for use with
// apply.
func IPClaimRef() *IPClaimRefApplyConfiguration {
	return &IPClaimRefApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *IPClaimRefApplyConfiguration) WithGroup(value string) *IPClaimRefApplyConfiguration {
	b.Group = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *IPClaimRefApplyConfiguration) WithResource(value string) *IPClaimRefApplyConfiguration {
	b.Resource = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IPClaimRefApplyConfiguration) WithName(value string) *IPClaimRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *IPClaimRefApplyConfiguration) WithUID(value types.UID) *IPClaimRefApplyConfiguration {
	b.UID = &value
	return b
}
