// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// NATGatewayAutoscalerSpecApplyConfiguration represents a declarative configuration of the NATGatewayAutoscalerSpec type for use
// with apply.
type NATGatewayAutoscalerSpecApplyConfiguration struct {
	NATGatewayRef *v1.LocalObjectReference `json:"natGatewayRef,omitempty"`
	MinPublicIPs  *int32                   `json:"minPublicIPs,omitempty"`
	MaxPublicIPs  *int32                   `json:"maxPublicIPs,omitempty"`
}

// NATGatewayAutoscalerSpecApplyConfiguration constructs a declarative configuration of the NATGatewayAutoscalerSpec type for use with
// apply.
func NATGatewayAutoscalerSpec() *NATGatewayAutoscalerSpecApplyConfiguration {
	return &NATGatewayAutoscalerSpecApplyConfiguration{}
}

// WithNATGatewayRef sets the NATGatewayRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NATGatewayRef field is set to the value of the last call.
func (b *NATGatewayAutoscalerSpecApplyConfiguration) WithNATGatewayRef(value v1.LocalObjectReference) *NATGatewayAutoscalerSpecApplyConfiguration {
	b.NATGatewayRef = &value
	return b
}

// WithMinPublicIPs sets the MinPublicIPs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinPublicIPs field is set to the value of the last call.
func (b *NATGatewayAutoscalerSpecApplyConfiguration) WithMinPublicIPs(value int32) *NATGatewayAutoscalerSpecApplyConfiguration {
	b.MinPublicIPs = &value
	return b
}

// WithMaxPublicIPs sets the MaxPublicIPs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPublicIPs field is set to the value of the last call.
func (b *NATGatewayAutoscalerSpecApplyConfiguration) WithMaxPublicIPs(value int32) *NATGatewayAutoscalerSpecApplyConfiguration {
	b.MaxPublicIPs = &value
	return b
}
