// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	internal "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NATGatewayAutoscalerApplyConfiguration represents a declarative configuration of the NATGatewayAutoscaler type for use
// with apply.
type NATGatewayAutoscalerApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *NATGatewayAutoscalerSpecApplyConfiguration `json:"spec,omitempty"`
	Status                           *corev1alpha1.NATGatewayAutoscalerStatus    `json:"status,omitempty"`
}

// NATGatewayAutoscaler constructs a declarative configuration of the NATGatewayAutoscaler type for use with
// apply.
func NATGatewayAutoscaler(name, namespace string) *NATGatewayAutoscalerApplyConfiguration {
	b := &NATGatewayAutoscalerApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("NATGatewayAutoscaler")
	b.WithAPIVersion("core.apinet.ironcore.dev/v1alpha1")
	return b
}

// ExtractNATGatewayAutoscaler extracts the applied configuration owned by fieldManager from
// nATGatewayAutoscaler. If no managedFields are found in nATGatewayAutoscaler for fieldManager, a
// NATGatewayAutoscalerApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// nATGatewayAutoscaler must be a unmodified NATGatewayAutoscaler API object that was retrieved from the Kubernetes API.
// ExtractNATGatewayAutoscaler provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractNATGatewayAutoscaler(nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscaler, fieldManager string) (*NATGatewayAutoscalerApplyConfiguration, error) {
	return extractNATGatewayAutoscaler(nATGatewayAutoscaler, fieldManager, "")
}

// ExtractNATGatewayAutoscalerStatus is the same as ExtractNATGatewayAutoscaler except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractNATGatewayAutoscalerStatus(nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscaler, fieldManager string) (*NATGatewayAutoscalerApplyConfiguration, error) {
	return extractNATGatewayAutoscaler(nATGatewayAutoscaler, fieldManager, "status")
}

func extractNATGatewayAutoscaler(nATGatewayAutoscaler *corev1alpha1.NATGatewayAutoscaler, fieldManager string, subresource string) (*NATGatewayAutoscalerApplyConfiguration, error) {
	b := &NATGatewayAutoscalerApplyConfiguration{}
	err := managedfields.ExtractInto(nATGatewayAutoscaler, internal.Parser().Type("com.github.ironcore-dev.ironcore-net.api.core.v1alpha1.NATGatewayAutoscaler"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(nATGatewayAutoscaler.Name)
	b.WithNamespace(nATGatewayAutoscaler.Namespace)

	b.WithKind("NATGatewayAutoscaler")
	b.WithAPIVersion("core.apinet.ironcore.dev/v1alpha1")
	return b, nil
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithKind(value string) *NATGatewayAutoscalerApplyConfiguration {
	b.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithAPIVersion(value string) *NATGatewayAutoscalerApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithName(value string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithGenerateName(value string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithNamespace(value string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithUID(value types.UID) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithResourceVersion(value string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithGeneration(value int64) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithCreationTimestamp(value metav1.Time) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *NATGatewayAutoscalerApplyConfiguration) WithLabels(entries map[string]string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *NATGatewayAutoscalerApplyConfiguration) WithAnnotations(entries map[string]string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *NATGatewayAutoscalerApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.OwnerReferences = append(b.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *NATGatewayAutoscalerApplyConfiguration) WithFinalizers(values ...string) *NATGatewayAutoscalerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.Finalizers = append(b.Finalizers, values[i])
	}
	return b
}

func (b *NATGatewayAutoscalerApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithSpec(value *NATGatewayAutoscalerSpecApplyConfiguration) *NATGatewayAutoscalerApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *NATGatewayAutoscalerApplyConfiguration) WithStatus(value corev1alpha1.NATGatewayAutoscalerStatus) *NATGatewayAutoscalerApplyConfiguration {
	b.Status = &value
	return b
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *NATGatewayAutoscalerApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.Name
}
