// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// NetworkInterfaceNATClaimRefApplyConfiguration represents a declarative configuration of the NetworkInterfaceNATClaimRef type for use
// with apply.
type NetworkInterfaceNATClaimRefApplyConfiguration struct {
	Name *string    `json:"name,omitempty"`
	UID  *types.UID `json:"uid,omitempty"`
}

// NetworkInterfaceNATClaimRefApplyConfiguration constructs a declarative configuration of the NetworkInterfaceNATClaimRef type for use with
// apply.
func NetworkInterfaceNATClaimRef() *NetworkInterfaceNATClaimRefApplyConfiguration {
	return &NetworkInterfaceNATClaimRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkInterfaceNATClaimRefApplyConfiguration) WithName(value string) *NetworkInterfaceNATClaimRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *NetworkInterfaceNATClaimRefApplyConfiguration) WithUID(value types.UID) *NetworkInterfaceNATClaimRefApplyConfiguration {
	b.UID = &value
	return b
}
