// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	net "github.com/ironcore-dev/ironcore-net/apimachinery/api/net"
	v1 "k8s.io/api/core/v1"
)

// ObjectIPApplyConfiguration represents an declarative configuration of the ObjectIP type for use
// with apply.
type ObjectIPApplyConfiguration struct {
	IPFamily *v1.IPFamily  `json:"ipFamily,omitempty"`
	Prefix   *net.IPPrefix `json:"prefix,omitempty"`
}

// ObjectIPApplyConfiguration constructs an declarative configuration of the ObjectIP type for use with
// apply.
func ObjectIP() *ObjectIPApplyConfiguration {
	return &ObjectIPApplyConfiguration{}
}

// WithIPFamily sets the IPFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPFamily field is set to the value of the last call.
func (b *ObjectIPApplyConfiguration) WithIPFamily(value v1.IPFamily) *ObjectIPApplyConfiguration {
	b.IPFamily = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *ObjectIPApplyConfiguration) WithPrefix(value net.IPPrefix) *ObjectIPApplyConfiguration {
	b.Prefix = &value
	return b
}
