// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	net "github.com/ironcore-dev/ironcore-net/apimachinery/api/net"
)

// PeeringPrefixApplyConfiguration represents a declarative configuration of the PeeringPrefix type for use
// with apply.
type PeeringPrefixApplyConfiguration struct {
	Name   *string       `json:"name,omitempty"`
	Prefix *net.IPPrefix `json:"prefix,omitempty"`
}

// PeeringPrefixApplyConfiguration constructs a declarative configuration of the PeeringPrefix type for use with
// apply.
func PeeringPrefix() *PeeringPrefixApplyConfiguration {
	return &PeeringPrefixApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PeeringPrefixApplyConfiguration) WithName(value string) *PeeringPrefixApplyConfiguration {
	b.Name = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *PeeringPrefixApplyConfiguration) WithPrefix(value net.IPPrefix) *PeeringPrefixApplyConfiguration {
	b.Prefix = &value
	return b
}
