// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TAPDeviceApplyConfiguration represents a declarative configuration of the TAPDevice type for use
// with apply.
type TAPDeviceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// TAPDeviceApplyConfiguration constructs a declarative configuration of the TAPDevice type for use with
// apply.
func TAPDevice() *TAPDeviceApplyConfiguration {
	return &TAPDeviceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TAPDeviceApplyConfiguration) WithName(value string) *TAPDeviceApplyConfiguration {
	b.Name = &value
	return b
}
