// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	net "github.com/ironcore-dev/ironcore-net/apimachinery/api/net"
)

// TargetNetworkInterfaceApplyConfiguration represents a declarative configuration of the TargetNetworkInterface type for use
// with apply.
type TargetNetworkInterfaceApplyConfiguration struct {
	IP        *net.IP                              `json:"ip,omitempty"`
	TargetRef *LocalUIDReferenceApplyConfiguration `json:"targetRef,omitempty"`
}

// TargetNetworkInterfaceApplyConfiguration constructs a declarative configuration of the TargetNetworkInterface type for use with
// apply.
func TargetNetworkInterface() *TargetNetworkInterfaceApplyConfiguration {
	return &TargetNetworkInterfaceApplyConfiguration{}
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *TargetNetworkInterfaceApplyConfiguration) WithIP(value net.IP) *TargetNetworkInterfaceApplyConfiguration {
	b.IP = &value
	return b
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *TargetNetworkInterfaceApplyConfiguration) WithTargetRef(value *LocalUIDReferenceApplyConfiguration) *TargetNetworkInterfaceApplyConfiguration {
	b.TargetRef = value
	return b
}
