apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patchesStrategicMerge:
  - patch-apiserver.yaml
  - patch-manager.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: ironcore-net-system
      name: ironcore-net-apiserver
    path: add-apiserver-args.yaml
