apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: onmetal-api-net-system
  name: onmetal-api-net-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
