apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apinet.api.onmetal.de:system:apinetlets
rules:
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - networks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
  - deletecollection
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - publicips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
  - deletecollection
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/networkpluginclient
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
