---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: apinet.api.onmetal.de:system:metalnetlets
rules:
- apiGroups:
    - apinet.api.onmetal.de
  resources:
    - networks
  verbs:
    - get
    - list
    - patch
    - update
    - watch
    - create
    - delete
