---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apinet.ironcore.dev:system:apinetlets
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/apinetletclient
  verbs:
  - create
- apiGroups:
  - core.apinet.ironcore.dev
  resources:
  - ips
  - loadbalancerroutings
  - loadbalancers
  - natgatewayautoscalers
  - natgateways
  - networkpolicies
  - networkpolicyrules
  - networks
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.apinet.ironcore.dev
  resources:
  - networkinterfaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
