apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: system
  name: apinet-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apinet-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
