apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: system
  name: apinet-role
rules:
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - networks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
- apiGroups:
  - apinet.api.onmetal.de
  resources:
  - publicips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
  - delete
