apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - apinet-rbac

patchesStrategicMerge:
  - patch-controller.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: apinetlet-system
      name: apinetlet-controller-manager
    path: add-manager-args.yaml
