apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- apinet-rbac

patches:
- path: patch-controller.yaml
- path: add-manager-args.yaml
  target:
    group: apps
    kind: Deployment
    name: apinetlet-controller-manager
    namespace: apinetlet-system
    version: v1
