// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/applyconfigurations/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkIDs implements NetworkIDInterface
type FakeNetworkIDs struct {
	Fake *FakeCoreV1alpha1
}

var networkidsResource = v1alpha1.SchemeGroupVersion.WithResource("networkids")

var networkidsKind = v1alpha1.SchemeGroupVersion.WithKind("NetworkID")

// Get takes name of the networkID, and returns the corresponding networkID object, and an error if there is any.
func (c *FakeNetworkIDs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkidsResource, name), &v1alpha1.NetworkID{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkID), err
}

// List takes label and field selectors, and returns the list of NetworkIDs that match those selectors.
func (c *FakeNetworkIDs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkIDList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkidsResource, networkidsKind, opts), &v1alpha1.NetworkIDList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkIDList{ListMeta: obj.(*v1alpha1.NetworkIDList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkIDList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkIDs.
func (c *FakeNetworkIDs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkidsResource, opts))
}

// Create takes the representation of a networkID and creates it.  Returns the server's representation of the networkID, and an error, if there is any.
func (c *FakeNetworkIDs) Create(ctx context.Context, networkID *v1alpha1.NetworkID, opts v1.CreateOptions) (result *v1alpha1.NetworkID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkidsResource, networkID), &v1alpha1.NetworkID{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkID), err
}

// Update takes the representation of a networkID and updates it. Returns the server's representation of the networkID, and an error, if there is any.
func (c *FakeNetworkIDs) Update(ctx context.Context, networkID *v1alpha1.NetworkID, opts v1.UpdateOptions) (result *v1alpha1.NetworkID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkidsResource, networkID), &v1alpha1.NetworkID{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkID), err
}

// Delete takes name of the networkID and deletes it. Returns an error if one occurs.
func (c *FakeNetworkIDs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(networkidsResource, name, opts), &v1alpha1.NetworkID{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkIDs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkidsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkIDList{})
	return err
}

// Patch applies the patch and returns the patched networkID.
func (c *FakeNetworkIDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkID, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkidsResource, name, pt, data, subresources...), &v1alpha1.NetworkID{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkID), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkID.
func (c *FakeNetworkIDs) Apply(ctx context.Context, networkID *corev1alpha1.NetworkIDApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkID, err error) {
	if networkID == nil {
		return nil, fmt.Errorf("networkID provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkID)
	if err != nil {
		return nil, err
	}
	name := networkID.Name
	if name == nil {
		return nil, fmt.Errorf("networkID.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkidsResource, *name, types.ApplyPatchType, data), &v1alpha1.NetworkID{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkID), err
}
