/*
 * Copyright (c) 2022 by the IronCore authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/ironcore-dev/ironcore-net/client-go/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DaemonSets returns a DaemonSetInformer.
	DaemonSets() DaemonSetInformer
	// IPs returns a IPInformer.
	IPs() IPInformer
	// IPAddresses returns a IPAddressInformer.
	IPAddresses() IPAddressInformer
	// Instances returns a InstanceInformer.
	Instances() InstanceInformer
	// LoadBalancers returns a LoadBalancerInformer.
	LoadBalancers() LoadBalancerInformer
	// LoadBalancerRoutings returns a LoadBalancerRoutingInformer.
	LoadBalancerRoutings() LoadBalancerRoutingInformer
	// NATGateways returns a NATGatewayInformer.
	NATGateways() NATGatewayInformer
	// NATGatewayAutoscalers returns a NATGatewayAutoscalerInformer.
	NATGatewayAutoscalers() NATGatewayAutoscalerInformer
	// NATTables returns a NATTableInformer.
	NATTables() NATTableInformer
	// Networks returns a NetworkInformer.
	Networks() NetworkInformer
	// NetworkIDs returns a NetworkIDInformer.
	NetworkIDs() NetworkIDInformer
	// NetworkInterfaces returns a NetworkInterfaceInformer.
	NetworkInterfaces() NetworkInterfaceInformer
	// Nodes returns a NodeInformer.
	Nodes() NodeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DaemonSets returns a DaemonSetInformer.
func (v *version) DaemonSets() DaemonSetInformer {
	return &daemonSetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPs returns a IPInformer.
func (v *version) IPs() IPInformer {
	return &iPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPAddresses returns a IPAddressInformer.
func (v *version) IPAddresses() IPAddressInformer {
	return &iPAddressInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Instances returns a InstanceInformer.
func (v *version) Instances() InstanceInformer {
	return &instanceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LoadBalancers returns a LoadBalancerInformer.
func (v *version) LoadBalancers() LoadBalancerInformer {
	return &loadBalancerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LoadBalancerRoutings returns a LoadBalancerRoutingInformer.
func (v *version) LoadBalancerRoutings() LoadBalancerRoutingInformer {
	return &loadBalancerRoutingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NATGateways returns a NATGatewayInformer.
func (v *version) NATGateways() NATGatewayInformer {
	return &nATGatewayInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NATGatewayAutoscalers returns a NATGatewayAutoscalerInformer.
func (v *version) NATGatewayAutoscalers() NATGatewayAutoscalerInformer {
	return &nATGatewayAutoscalerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NATTables returns a NATTableInformer.
func (v *version) NATTables() NATTableInformer {
	return &nATTableInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Networks returns a NetworkInformer.
func (v *version) Networks() NetworkInformer {
	return &networkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NetworkIDs returns a NetworkIDInformer.
func (v *version) NetworkIDs() NetworkIDInformer {
	return &networkIDInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// NetworkInterfaces returns a NetworkInterfaceInformer.
func (v *version) NetworkInterfaces() NetworkInterfaceInformer {
	return &networkInterfaceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Nodes returns a NodeInformer.
func (v *version) Nodes() NodeInformer {
	return &nodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
