// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	internalinterfaces "github.com/ironcore-dev/ironcore-net/client-go/informers/externalversions/internalinterfaces"
	versioned "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IPAddressInformer provides access to a shared informer and lister for
// IPAddresses. Prefer using the type-safe variant (see [TypedIPAddressInformer]).
type IPAddressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.IPAddressLister
}

// TypedIPAddressInformer provides access to a shared informer and lister for
// IPAddresses, including the type-safe TypedInformer variant.
// It is a superset of IPAddressInformer.
type TypedIPAddressInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() IPAddressIndexInformer
	Lister() corev1alpha1.IPAddressLister
}

// IPAddressIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type IPAddressIndexInformer cache.TypedSharedIndexInformer[*apicorev1alpha1.IPAddress]

// IPAddressHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for IPAddress.
type IPAddressHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apicorev1alpha1.IPAddress]

// IPAddressDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for IPAddress.
type IPAddressDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apicorev1alpha1.IPAddress]

// IPAddressFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for IPAddress.
type IPAddressFilteringHandler = cache.TypedFilteringResourceEventHandler[*apicorev1alpha1.IPAddress]

// IPAddressIndexers is a specialization of [cache.TypedIndexers] for IPAddress.
type IPAddressIndexers = cache.TypedIndexers[*apicorev1alpha1.IPAddress]

// DeletedIPAddress is a specialization of [cache.DeletedObject] for IPAddress.
type DeletedIPAddress = cache.DeletedObject[*apicorev1alpha1.IPAddress]

type iPAddressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIPAddressInformer constructs a new informer for IPAddress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedIPAddressInformer]).
func NewIPAddressInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewIPAddressInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedIPAddressInformer constructs a new informer for IPAddress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedIPAddressInformer(client versioned.Interface, resyncPeriod time.Duration, indexers IPAddressIndexers) IPAddressIndexInformer {
	return NewTypedIPAddressInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredIPAddressInformer constructs a new informer for IPAddress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredIPAddressInformer]).
func NewFilteredIPAddressInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedIPAddressInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredIPAddressInformer constructs a new informer for IPAddress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredIPAddressInformer(client versioned.Interface, resyncPeriod time.Duration, indexers IPAddressIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) IPAddressIndexInformer {
	return NewTypedIPAddressInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewIPAddressInformerWithOptions constructs a new informer for IPAddress type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedIPAddressInformerWithOptions]).
func NewIPAddressInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedIPAddressInformerWithOptions(client, options)
}

// NewTypedIPAddressInformerWithOptions constructs a new informer for IPAddress type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedIPAddressInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) IPAddressIndexInformer {
	gvr := schema.GroupVersionResource{Group: "core.apinet.ironcore.dev", Version: "v1alpha1", Resource: "ipaddresss"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.IPAddress](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().IPAddresses().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().IPAddresses().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().IPAddresses().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().IPAddresses().Watch(ctx, opts)
			},
		}, client),
		&apicorev1alpha1.IPAddress{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *iPAddressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedIPAddressInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *iPAddressInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *iPAddressInformer) TypedInformer() IPAddressIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.IPAddress](f.factory.InformerFor(&apicorev1alpha1.IPAddress{}, f.defaultInformer))
}

func (f *iPAddressInformer) Lister() corev1alpha1.IPAddressLister {
	return corev1alpha1.NewIPAddressLister(f.Informer().GetIndexer())
}

// ToTypedIPAddressInformer converts an untyped informer into a TypedIPAddressInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *IPAddress. If that is not the case, calling type-safe methods of the returned
// TypedIPAddressInformer leads to runtime panics. A safer alternative is to pass
// around a TypedIPAddressInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedIPAddressInformer(informer IPAddressInformer) TypedIPAddressInformer {
	if informer, ok := informer.(TypedIPAddressInformer); ok {
		return informer
	}
	return &iPAddressTypedInformerAdapter{informer}
}

type iPAddressTypedInformerAdapter struct {
	IPAddressInformer
}

func (a *iPAddressTypedInformerAdapter) TypedInformer() IPAddressIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.IPAddress](a.Informer())
}

// ToIPAddressIndexInformer converts an untyped informer into a IPAddressIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *IPAddress. If that is not the case, calling type-safe methods of the returned
// IPAddressIndexInformer leads to runtime panics. A safer alternative is to pass
// around a IPAddressIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToIPAddressIndexInformer(informer cache.SharedIndexInformer) IPAddressIndexInformer {
	if informer, ok := informer.(IPAddressIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.IPAddress](informer)
}
