// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	internalinterfaces "github.com/ironcore-dev/ironcore-net/client-go/informers/externalversions/internalinterfaces"
	versioned "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NATTableInformer provides access to a shared informer and lister for
// NATTables. Prefer using the type-safe variant (see [TypedNATTableInformer]).
type NATTableInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.NATTableLister
}

// TypedNATTableInformer provides access to a shared informer and lister for
// NATTables, including the type-safe TypedInformer variant.
// It is a superset of NATTableInformer.
type TypedNATTableInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() NATTableIndexInformer
	Lister() corev1alpha1.NATTableLister
}

// NATTableIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type NATTableIndexInformer cache.TypedSharedIndexInformer[*apicorev1alpha1.NATTable]

// NATTableHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for NATTable.
type NATTableHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apicorev1alpha1.NATTable]

// NATTableDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for NATTable.
type NATTableDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apicorev1alpha1.NATTable]

// NATTableFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for NATTable.
type NATTableFilteringHandler = cache.TypedFilteringResourceEventHandler[*apicorev1alpha1.NATTable]

// NATTableIndexers is a specialization of [cache.TypedIndexers] for NATTable.
type NATTableIndexers = cache.TypedIndexers[*apicorev1alpha1.NATTable]

// DeletedNATTable is a specialization of [cache.DeletedObject] for NATTable.
type DeletedNATTable = cache.DeletedObject[*apicorev1alpha1.NATTable]

type nATTableInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNATTableInformer constructs a new informer for NATTable type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedNATTableInformer]).
func NewNATTableInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewNATTableInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedNATTableInformer constructs a new informer for NATTable type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedNATTableInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers NATTableIndexers) NATTableIndexInformer {
	return NewTypedNATTableInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredNATTableInformer constructs a new informer for NATTable type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredNATTableInformer]).
func NewFilteredNATTableInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedNATTableInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredNATTableInformer constructs a new informer for NATTable type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredNATTableInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers NATTableIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) NATTableIndexInformer {
	return NewTypedNATTableInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewNATTableInformerWithOptions constructs a new informer for NATTable type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedNATTableInformerWithOptions]).
func NewNATTableInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedNATTableInformerWithOptions(client, namespace, options)
}

// NewTypedNATTableInformerWithOptions constructs a new informer for NATTable type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedNATTableInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) NATTableIndexInformer {
	gvr := schema.GroupVersionResource{Group: "core.apinet.ironcore.dev", Version: "v1alpha1", Resource: "nattables"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NATTable](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NATTables(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NATTables(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NATTables(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NATTables(namespace).Watch(ctx, opts)
			},
		}, client),
		&apicorev1alpha1.NATTable{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *nATTableInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedNATTableInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *nATTableInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *nATTableInformer) TypedInformer() NATTableIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NATTable](f.factory.InformerFor(&apicorev1alpha1.NATTable{}, f.defaultInformer))
}

func (f *nATTableInformer) Lister() corev1alpha1.NATTableLister {
	return corev1alpha1.NewNATTableLister(f.Informer().GetIndexer())
}

// ToTypedNATTableInformer converts an untyped informer into a TypedNATTableInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *NATTable. If that is not the case, calling type-safe methods of the returned
// TypedNATTableInformer leads to runtime panics. A safer alternative is to pass
// around a TypedNATTableInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedNATTableInformer(informer NATTableInformer) TypedNATTableInformer {
	if informer, ok := informer.(TypedNATTableInformer); ok {
		return informer
	}
	return &nATTableTypedInformerAdapter{informer}
}

type nATTableTypedInformerAdapter struct {
	NATTableInformer
}

func (a *nATTableTypedInformerAdapter) TypedInformer() NATTableIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NATTable](a.Informer())
}

// ToNATTableIndexInformer converts an untyped informer into a NATTableIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *NATTable. If that is not the case, calling type-safe methods of the returned
// NATTableIndexInformer leads to runtime panics. A safer alternative is to pass
// around a NATTableIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToNATTableIndexInformer(informer cache.SharedIndexInformer) NATTableIndexInformer {
	if informer, ok := informer.(NATTableIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NATTable](informer)
}
