// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ironcore-dev/ironcore-net/api/core/v1alpha1"
	internalinterfaces "github.com/ironcore-dev/ironcore-net/client-go/informers/externalversions/internalinterfaces"
	versioned "github.com/ironcore-dev/ironcore-net/client-go/ironcorenet/versioned"
	corev1alpha1 "github.com/ironcore-dev/ironcore-net/client-go/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkIDInformer provides access to a shared informer and lister for
// NetworkIDs. Prefer using the type-safe variant (see [TypedNetworkIDInformer]).
type NetworkIDInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.NetworkIDLister
}

// TypedNetworkIDInformer provides access to a shared informer and lister for
// NetworkIDs, including the type-safe TypedInformer variant.
// It is a superset of NetworkIDInformer.
type TypedNetworkIDInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() NetworkIDIndexInformer
	Lister() corev1alpha1.NetworkIDLister
}

// NetworkIDIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type NetworkIDIndexInformer cache.TypedSharedIndexInformer[*apicorev1alpha1.NetworkID]

// NetworkIDHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for NetworkID.
type NetworkIDHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apicorev1alpha1.NetworkID]

// NetworkIDDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for NetworkID.
type NetworkIDDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apicorev1alpha1.NetworkID]

// NetworkIDFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for NetworkID.
type NetworkIDFilteringHandler = cache.TypedFilteringResourceEventHandler[*apicorev1alpha1.NetworkID]

// NetworkIDIndexers is a specialization of [cache.TypedIndexers] for NetworkID.
type NetworkIDIndexers = cache.TypedIndexers[*apicorev1alpha1.NetworkID]

// DeletedNetworkID is a specialization of [cache.DeletedObject] for NetworkID.
type DeletedNetworkID = cache.DeletedObject[*apicorev1alpha1.NetworkID]

type networkIDInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNetworkIDInformer constructs a new informer for NetworkID type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedNetworkIDInformer]).
func NewNetworkIDInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewNetworkIDInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedNetworkIDInformer constructs a new informer for NetworkID type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedNetworkIDInformer(client versioned.Interface, resyncPeriod time.Duration, indexers NetworkIDIndexers) NetworkIDIndexInformer {
	return NewTypedNetworkIDInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredNetworkIDInformer constructs a new informer for NetworkID type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredNetworkIDInformer]).
func NewFilteredNetworkIDInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedNetworkIDInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredNetworkIDInformer constructs a new informer for NetworkID type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredNetworkIDInformer(client versioned.Interface, resyncPeriod time.Duration, indexers NetworkIDIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) NetworkIDIndexInformer {
	return NewTypedNetworkIDInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewNetworkIDInformerWithOptions constructs a new informer for NetworkID type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedNetworkIDInformerWithOptions]).
func NewNetworkIDInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedNetworkIDInformerWithOptions(client, options)
}

// NewTypedNetworkIDInformerWithOptions constructs a new informer for NetworkID type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedNetworkIDInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) NetworkIDIndexInformer {
	gvr := schema.GroupVersionResource{Group: "core.apinet.ironcore.dev", Version: "v1alpha1", Resource: "networkids"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NetworkID](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NetworkIDs().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NetworkIDs().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NetworkIDs().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CoreV1alpha1().NetworkIDs().Watch(ctx, opts)
			},
		}, client),
		&apicorev1alpha1.NetworkID{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *networkIDInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedNetworkIDInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *networkIDInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *networkIDInformer) TypedInformer() NetworkIDIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NetworkID](f.factory.InformerFor(&apicorev1alpha1.NetworkID{}, f.defaultInformer))
}

func (f *networkIDInformer) Lister() corev1alpha1.NetworkIDLister {
	return corev1alpha1.NewNetworkIDLister(f.Informer().GetIndexer())
}

// ToTypedNetworkIDInformer converts an untyped informer into a TypedNetworkIDInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *NetworkID. If that is not the case, calling type-safe methods of the returned
// TypedNetworkIDInformer leads to runtime panics. A safer alternative is to pass
// around a TypedNetworkIDInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedNetworkIDInformer(informer NetworkIDInformer) TypedNetworkIDInformer {
	if informer, ok := informer.(TypedNetworkIDInformer); ok {
		return informer
	}
	return &networkIDTypedInformerAdapter{informer}
}

type networkIDTypedInformerAdapter struct {
	NetworkIDInformer
}

func (a *networkIDTypedInformerAdapter) TypedInformer() NetworkIDIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NetworkID](a.Informer())
}

// ToNetworkIDIndexInformer converts an untyped informer into a NetworkIDIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *NetworkID. If that is not the case, calling type-safe methods of the returned
// NetworkIDIndexInformer leads to runtime panics. A safer alternative is to pass
// around a NetworkIDIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToNetworkIDIndexInformer(informer cache.SharedIndexInformer) NetworkIDIndexInformer {
	if informer, ok := informer.(NetworkIDIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.NetworkID](informer)
}
