apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - apinet-rbac

patches:
  - path: patch-controller.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: metalnetlet-system
      name: metalnetlet-controller-manager
    path: add-manager-args.yaml
