apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metalnetlet-system
namePrefix: metalnetlet-

resources:
  - ../../metalnet-rbac

patches:
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: controller-manager
        namespace: system
